CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE role (
    admin BOOLEAN NOT NULL,
    is_user BOOLEAN NOT NULL
);

CREATE TABLE users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY, 
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    phone_number VARCHAR(15),
    role VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
);

